<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="#" />
    <link rel="stylesheet" href="bootstrap4/css/bootstrap.min.css">
    <link rel="stylesheet" href="estilos.css">
    <!-- titre de ma page -->
    <title>Inmobilier LC</title>
    <!-- css -->
    <link rel="stylesheet" href="../css/style.css">
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<!-- site web -->

<body>
    <header style="height: 70px">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Inmobilier LC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="index.php">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="formulaire.php">Ajouter un bien inmobilier</a>
                        </li>   
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <!-- Default form contact -->
        <form class="text-center border border-light p-5" action="index.php" method="post" class="needs-validation" novalidate>

            <h2 class="h4 mb-4">Formulaire</h2>

            <!-- Titre -->
            <label for="titre"></label>
            <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="Titre" name="titre">
            <div class="valid-feedback">¡Ok valide!</div>
            <div class="invalid-feedback">Completez le champ.</div>   

            <!-- adresse -->
            <label for="adresse"></label>
            <input type="text" id="defaultContactFormEmail" class="form-control mb-4" placeholder="Adresse"name="adresse">
            <div class="valid-feedback">¡Ok valide!</div>
            <div class="invalid-feedback">Completez le champ.</div>

            <!-- code postal -->
            <label for="codePostal"></label>
            <input type="text" id="defaultContactFormEmail" class="form-control mb-4" placeholder="Ville" name="ville">
            <div class="valid-feedback">¡Ok valide!</div>
            <div class="invalid-feedback">Completez le champ.</div>

            <!-- surface -->
            <label for="surface"></label>
            <input type="text" id="defaultContactFormEmail" class="form-control mb-4" placeholder="Code postal" name="surface">
            <div class="valid-feedback">¡Ok valide!</div>
            <div class="invalid-feedback">Completez le champ.</div>

            <!-- prix -->
            <label for="prix"></label>
            <input type="text" id="defaultContactFormEmail" class="form-control mb-4" placeholder="Surface" name="surface">
            <div class="valid-feedback">¡Ok valide!</div>
            <div class="invalid-feedback">Completez le champ.</div>

            
            <!-- type -->
            <label>Type</label>
            <select class="browser-default custom-select mb-4">
                <option value="" disabled selected>Choisissez votre option</option>
                <option value="3">Location</option>
                <option value="4">Vente</option>
            </select>

            <!-- description -->
            <div class="form-group">
            <label>Description</label>
                <textarea class="form-control rounded-0" id="exampleFormControlTextarea2" rows="3" placeholder="Message"></textarea>
            </div>

            <!-- Photo -->
            <div class="custom-control custom-checkbox mb-4">
                <input type="checkbox" class="custom-control-input" id="defaultContactFormCopy">
                <label class="custom-control-label" for="defaultContactFormCopy">Send me a copy of this message</label>
            </div>

            <!-- Send button -->
            <button class="btn btn-info btn-block" type="submit">Soumettre</button>

        </form>
    </main>

    <script src="jquery/jquery-3.3.1.min.js"></script>
    <script src="popper/popper.min.js"></script>
    <script src="bootstrap4/js/bootstrap.min.js"></script>
    <script src="../js/code.js"></script>

</body>

</html>