<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="#" />
    <link rel="stylesheet" href="bootstrap4/css/bootstrap.min.css">
    <link rel="stylesheet" href="estilos.css">
    <!-- titre de ma page -->
    <title>Inmobilier LC</title>
    <!-- css -->
    <link rel="stylesheet" href="../css/style.css">
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<!-- site web -->

<body>
    <header style="height: 70px">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="index.php">Immobilier LC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="index.php">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="formulaire.php">Deposer un annonce</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
            <h1><?=$pageTitle;?></h1>

            <div class="block">

                <div class="card">

                    <div class="row">
                        <section>
                            <div class="col img">
                                <!-- pour Aficher L'image du logement -->
                                <img src="../Images/<?= $logement['photo']; ?>" id="car" alt="Image d'un logement" width="75%">
                            </div>
                        </section>
                        <section>
                            <div class="col card-body ">
                                <!-- On Recupere le titre du logement -->
                                <a href="#">
                                    <h5 class="card-title"><?= $logement['titre']; ?></h5>
                                </a>
                                <!-- On Recupere le type du logement -->
                                <p class="card-text">Type:<br><?= $logement['type']; ?></p>
                                <!-- On recupere la description du logemnt  -->
                                <p class="card-text">Description:<br><?= $logement['description']; ?></p>
                                <!-- On Recupere la surface du logement-->
                                <p class="card-text">Surface:<br><?= $logement['surface']; ?>m²</p>
                                <!-- On Recupere la ville du logement  -->
                                <p class="card-text">Ville:<br><?= $logement['ville']; ?></p>
                                <!-- On Recupere le code postal du logement -->
                                <p class="card-text">Code postale:<br><?= $logement['cp']; ?></p>
                                <!-- On Recupere le prix du logement -->
                                <p class="card-text">Prix:<br><?= $logement['prix']; ?>£</p>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
    </main>

    <script src="jquery/jquery-3.3.1.min.js"></script>
    <script src="popper/popper.min.js"></script>
    <script src="bootstrap4/js/bootstrap.min.js"></script>
    <script src="../js/code.js"></script>

</body>

</html>